### PR TITLE
Minor interface description changes

### PR DESCRIPTION
**Pull request by maruk0chan**
Minor bugs fixed for to-do list tasks #29, #31, #42.

### CODE REVIEW

**Comment by maruk0chan** [comment]
changed the favicon (with white background)

**Comment by maruk0chan** [comment]
Bugfix#23

Instead of creating a new getter, I have made use of the existing getter "activeDataset" to make the description "Compare with comma separated ${this.activeDataset.gene.header} list".

Since there is no "this.activeDataset.gene.header" in Mouse Fantom 5, "RES ID" is now being used temporarily.

**Comment by gstein314** [comment]
@maruk0chan 
Bugfix 29, 31, 38, 42 are OK.

Regarding Bugfix 23, please rethink the conditional branching in light of the RES ID. Thank you in advance.

**Comment by maruk0chan** [comment]
Fixed the issue that the description did not change when pressing "SAMPLE" filter.
Part of the code is changed to be switch statement.

**Comment by gstein314** [comment]
@maruk0chan 
Thank you for your assistance. As for the content, it is as we discussed in Pair Pro. 
I will merge them once. Thank you for your continued help.

**Pull request merged**
