### PR TITLE
Feature/medians after download

### PR DESCRIPTION
**Pull request by maruk0chan**
1. Combine annotation column into description and symbol columns
2. Index Search button color (Blue --> Orange) and Gray when disabled
3. Multisort sorting for string becomes case insensitive
4. Chr order 1~22, X, Y, MT
5. Delete gene expression url
6. Download with combined median

### CODE REVIEW

**Comment by maruk0chan** [comment]
1. Correct alias format
2. Fix tsv file name and comparison button
3.  Sub-button style
4. Correct typo 'fecthing'
5. Refactor sorters for Chr position
6. Delete unused circle mark for alias

**Comment by maruk0chan** [comment]
Major improvement : Move the filtering and sorting data logic from ProjectResult to _project
and delete some unused code and variables

**Comment by maruk0chan** [comment]
1. Fix function not in scope problems
2. Icon clickable area
3. Minor UI appearance improvement

**Comment by gstein314** [comment]
@maruk0chan 
thank you. Discuss the details later.

**Pull request merged**
